version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto-21
    commands:
      - echo Installing Amazon Corretto 21...
      - yum update -y
      - yum install -y java-21-amazon-corretto-devel
  pre_build:
    commands:
      - echo Nothing to do in the pre_build phase
  build:
    commands:
      - echo Build started on $(date)
      - ./gradlew clean build publish
  post_build:
    commands:
      - echo Build completed on $(date)
artifacts:
  files:
    - 'build/libs/*.war'