version: 0.2

phases:
  install:
    commands:
      - echo Installing Amazon Corretto 21 manually...
      - yum update -y
      - yum install -y wget tar
      - wget https://corretto.aws/downloads/latest/amazon-corretto-21-x64-linux-jdk.tar.gz
      - mkdir -p /usr/lib/jvm
      - tar -xvzf amazon-corretto-21-x64-linux-jdk.tar.gz -C /usr/lib/jvm
      - mv /usr/lib/jvm/amazon-corretto-21* /usr/lib/jvm/amazon-corretto-21
      - export JAVA_HOME=/usr/lib/jvm/amazon-corretto-21
      - export PATH=$JAVA_HOME/bin:$PATH
      - java -version
  pre_build:
    commands:
      - echo Nothing to do in the pre_build phase
  build:
    commands:
      - echo Build started on $(date)
      - ./gradlew clean build publish
  post_build:
    commands:
      - echo Build completed on $(date)
artifacts:
  files:
    - 'build/libs/*.war'